### ISSUE TITLE
Make python/rayon dependencies optional

### ISSUE THREAD

**Issue by dvtomas** [bast/polygons#11]
I really just need the code to compute inside/outside, and the distance from polygon. Rayon/Python dependencies are a burden to me, but I understand for others it's a crucial piece of the code. I suggest making those two dependencies (independently) optional.

**Comment by bast** [comment]
Thanks for the good suggestion and the fix!

**Comment by dvtomas** [comment]
Thank you for merging. Would you mind releasing a new version, please?

**Comment by bast** [comment]
I will do that. I hope it will not take me longer than 1 day.

**Comment by bast** [comment]
Version 0.3.1 is out. Thanks again!
