### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by u200915986** [bast/polygons#6]
ERROR: Command errored out with exit status 4294967295:
     command: 'c:\Users\\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-req-build-cvo_l3i0\\setup.py'"'"'; __file__='"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-req-build-cvo_l3i0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\\AppData\Local\Temp\pip-record-cqk1526x\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\Users\\anaconda3\Include\polygons'
         cwd: C:\Users\\AppData\Local\Temp\pip-req-build-cvo_l3i0\
    Complete output (14 lines):
    c:\Users\\anaconda3\lib\site-packages\setuptools\dist.py:454: UserWarning: Normalizing '0.0.0-alpha-1' to '0.0.0a1'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    c:\Users\\anaconda3\Scripts\cmake.exe -DCMAKE_BUILD_TYPE=release -DENABLE_OPENMP=True ..
    -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
    -- Found OpenMP_C: -openmp
    -- Found OpenMP_CXX: -openmp
    -- Found OpenMP: TRUE
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users//AppData/Local/Temp/pip-req-build-cvo_l3i0/build_setup_py
    make
    Error while running Make
    ----------------------------------------
ERROR: Command errored out with exit status 4294967295: 'c:\Users\\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-req-build-cvo_l3i0\\setup.py'"'"'; __file__='"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-req-build-cvo_l3i0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\\AppData\Local\Temp\pip-record-cqk1526x\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\Users\\anaconda3\Include\polygons' Check the logs for full command output

**Comment by bast** [comment]
Sorry for the troubles!
It seems you are using Windows, which version?
Have you tried with the Windows Subsystem for Linux (WSL)?

And can you please describe what you would like to do with the code? I am asking because I am currently working on a rewrite to Rust which I will soon make conda-installable: https://github.com/bast/polygons-rs

**Comment by u200915986** [comment]
Bast.

Yes， I am using windows 10, 1909;v the latest update.
I installed the anaconda with the python 3.6 and python .27.

I am not familiar with linux.

I am a economics researcher , and want to find the 
location in or out the zone, and the distance to the border of the
zone. the then test the effect of the  zone.
 I think you did a great job for people not good at programming. would you
to do some work to make the code run on windows?

Thanks a lot!

**Comment by bast** [comment]
I will try to restore it but also working on creating a Python interface to https://github.com/bast/polygons-rs and sharing it via Conda. You plan to use the code within Python? And how many points will your example approximately have?

**Comment by u200915986** [comment]
yes，I want to do it use python，I have about 300000points to find in or out
polygons.

thanks！

Radovan Bast <notifications@github.com>于2020年4月30日 周四下午4:46写道：

**Comment by bast** [comment]
Great. I will try to fix it this week.

**Comment by bast** [comment]
I almost have a new version ready (Python interface with Rust implementation below). I will soon put it on https://test.pypi.org/ and maybe you can help me testing it?

**Comment by u200915986** [comment]
that is a quick and great work，I cannot waiting to run my data.

**Comment by bast** [comment]
I am testing the new code and it seems to work on Linux, Windows, and macOS. I will publish a new version in the next 2-3 days.

**Comment by bast** [comment]
It will hopefully work now - please try.

Note that both the installation and the API changed slightly:
https://github.com/bast/polygons/blob/master/README.rst

Please let me know how it worked.

**Comment by u200915986** [comment]
Dear Bast, 

could you update the read the points and polygons from Excel file , and add excel sample file? I just beginner with python, and I have mang million points and 1 thousands   pythons in excel format. which will great help to to use this program.   
Anyway, this is a great program to deal this question.(I have found for a long time to find it )

**Comment by bast** [comment]
Could you create an example Excel sheet with some anonymized data just to see how you store it? Does not have to be many points and many polygons. Then I can add an example on how to use this with Excel.

**Comment by u200915986** [comment]
[polygons.xlsx](https://github.com/bast/polygons/files/4674873/polygons.xlsx)
[pointss.xlsx](https://github.com/bast/polygons/files/4674874/pointss.xlsx)


Dear Bast,
 sorry for delayed reply.

the attached files are the points to find in or out of polygons, and then get the positive distance if the points out of the polygons, and negative distance if the points in the polygons.

Best regards!

Kei

**Comment by bast** [comment]
Python can work with `xlsx` files but it's much easier to work with `csv` files and you can export/import `csv` files from/to your spreadsheet program.

I did this and created a `points.csv` file:
```csv
num,lat,lon
3186,121.679333,31.223931
606,121.640767,31.235085
409,121.361676,31.265641
2194,121.447488,30.940532
3346,121.13404,31.233794
373,121.263817,31.024829
1863,121.265109,31.023588
3229,121.330854,31.324156
3241,121.334817,30.706894
51,121.448566,31.048938
1663,121.641066,31.234967
4509,121.365019,31.271424
3203,121.483268,31.171252
4475,121.363267,31.108026
2919,121.512313,31.275524
2578,121.619884,31.320811
...
```

And a `polygons.csv` file:
```csv
number,lat,lon
1,117.0803,30.5636
1,117.0816,30.5534
1,117.0831,30.5408
1,117.0831,30.5378
1,117.0838,30.5338
1,117.0732,30.5366
1,117.0599,30.5392
1,117.0523,30.5393
1,117.0493,30.5410
1,117.0438,30.5492
1,117.0304,30.5592
1,117.0282,30.5698
1,117.0282,30.5764
1,117.0408,30.5733
1,117.0548,30.5688
1,117.0675,30.5655
1,117.0803,30.5636
2,114.3831,36.0775
2,114.3831,36.0721
2,114.3831,36.0662
2,114.3831,36.0645
2,114.3830,36.0621
2,114.3727,36.0622
2,114.3613,36.0619
2,114.3563,36.0620
2,114.3490,36.0617
2,114.3488,36.0684
2,114.3488,36.0754
2,114.3488,36.0767
2,114.3490,36.0789
2,114.3590,36.0778
2,114.3678,36.0779
2,114.3787,36.0775
2,114.3831,36.0775
```

Then you can use the following script:
```python
import csv
import polygons


def read_points(file_name):
    points = []
    with open(file_name) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            x = float(row["lon"])
            y = float(row["lat"])
            points.append((x, y))
    return points


def read_polygons(file_name):
    polygon_points = []
    with open(file_name) as csvfile:
        reader = csv.DictReader(csvfile)
        i = 0
        for row in reader:
            n = int(row["number"])
            if n > i:
                if i > 0:
                    polygon_points.append(polygon)
                polygon = []
                i = n
            x = float(row["lon"])
            y = float(row["lat"])
            polygon.append((x, y))
    return polygon_points


if __name__ == "__main__":
    points = read_points("points.csv")

    polygon_points = read_polygons("polygons.csv")

    num_edges_children = 4
    num_nodes_children = 4
    tree = polygons.build_tree(polygon_points, num_edges_children, num_nodes_children)

    inside = polygons.points_are_inside(tree, points)

    # the units are problematic, see explanation below 
    distances = polygons.distances_nearest_edges(tree, points)

    print("inside,distance,signed distance")
    for is_in, distance in zip(inside, distances):
        if is_in:
            signed_distance = -distance
        else:
            signed_distance = distance
        print(f"{is_in},{distance},{signed_distance}")
```

However, two important points to consider:
1. The code assumes that the polygons are flat and the "earth is flat". I plan to implement polygon distances etc. on a sphere (#7) but this is not done yet. This works for cases where the projection is a good approximation of a polygon but for very large polygons which are then "curved", this will not work.
2. The distance is now computed in the same units as the input units (lat/lon) but I am not sure what that means. So you should probably first project the lat-lon onto some (m or km) x-y coordinates so that the distance can also be computed in m or km.

**Comment by bast** [comment]
Closing this issue since it's not an install problem anymore but please reopen a new one if some problems show up.
