### ISSUE TITLE
Also give index of nearest point and index of polygon if inside polygon

### ISSUE THREAD

**Issue by cuicuicui888** [bast/polygons#8]
Excuse me, I'm sorry to bother you. There are some questions i would like to ask you during the operation of the existing program.
First, when viewing the distance from a point to a polygon, a point can only output the distance to one polygon. Is this output polygon the nearest polygon to this point?
Second, If the polygon mentioned above is the nearest polygon, can we know which polygon it is? How can we output the information for this polygon?(For example, the name or information of a school district)
Third, the program that estimates whether a point is in a polygon does not say which polygon it is in, so how can we get the name or information of the polygon?
Thank you for taking time out of your busy schedule to answer my questions. Wish you all the best in your work!

**Comment by bast** [comment]
> First, when viewing the distance from a point to a polygon, a point can only output the distance to one polygon. Is this output polygon the nearest polygon to this point?

Yes.

> Second, If the polygon mentioned above is the nearest polygon, can we know which polygon it is? How can we output the information for this polygon?(For example, the name or information of a school district)

This used to be possible but I have removed that functionality I think but I will reintroduce it so that we not only know the nearest distance but also the index of the nearest point.

> Third, the program that estimates whether a point is in a polygon does not say which polygon it is in, so how can we get the name or information of the polygon?

Same as above ... this is something I should reintroduce. I will work on it soon.

> Thank you for taking time out of your busy schedule to answer my questions. Wish you all the best in your work!

Thanks for your interest in it :-)

**Comment by cuicuicui888** [comment]
thank you very much for your reply!
| |
崔珈寧 中南財經政法大學
|
|
cuijnnn@163.com
|
签名由网易邮箱大师定制
On 9/3/2020 00:38，Radovan Bast<notifications@github.com> wrote：

First, when viewing the distance from a point to a polygon, a point can only output the distance to one polygon. Is this output polygon the nearest polygon to this point?

Yes.

Second, If the polygon mentioned above is the nearest polygon, can we know which polygon it is? How can we output the information for this polygon?(For example, the name or information of a school district)

This used to be possible but I have removed that functionality I think but I will reintroduce it so that we not only know the nearest distance but also the index of the nearest point.

Third, the program that estimates whether a point is in a polygon does not say which polygon it is in, so how can we get the name or information of the polygon?

Same as above ... this is something I should reintroduce. I will work on it soon.

Thank you for taking time out of your busy schedule to answer my questions. Wish you all the best in your work!

Thanks for your interest in it :-)

**Comment by bast** [comment]
It's a busy month here but I will work on this in October.

**Comment by bast** [comment]
I have now implemented also nearest indices, not only distances. Note that one function name changed name (see the example).

The indexing of polygons I need to postpone since this does not fit yet well into the current code structure.

**Comment by bast** [comment]
I thought more about this. You could solve it by using both `points_are_inside` and `distances_nearest_vertices`. The latter gives you also the closest point. You could keep a mapping point number -> polygon number, and with this you could find out inside which polygon a point was found.
